version: '3.8'
services:
  app:
    build: .
    ports:
      - "6969:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://admin:example@mongo:27017/emails
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "7070:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
