spring.resources.static-locations=classpath:/static/,file:./uploads/
app.pdf.templatePath=form_template.pdf
app.pdf.fontFamily=times.ttf
app.pdf.encoding=Cp1250
app.pdf.fontSize=12
spring.servlet.multipart.max-file-size=100GB
spring.servlet.multipart.max-request-size=100GB
spring.data.mongodb.uri=mongodb://admin:example@localhost:27018/emails?authSource=admin
attachments.directory=/app/attachments

# Synology NAS configuration
synology.host=
synology.username=
synology.password=
synology.path-prefix=/volume1
synology.local-mount-prefix=/mnt/nas
synology.search-extensions=pst,ost
synology.batch-size=100

logging.level.root=info
logging.file.name=logs/app.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} - %msg%n